@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Sep 14 02:52:18 +0200 2024
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim surf_top_behav -key {Behavioral:sim_1:Functional:surf_top} -tclbatch surf_top.tcl -log simulate.log -testplusarg UVM_TESTNAME=test_surf_simple -testplusarg UVM_VERBOSITY=UVM_MEDIUM"
call xsim  surf_top_behav -key {Behavioral:sim_1:Functional:surf_top} -tclbatch surf_top.tcl -log simulate.log -testplusarg UVM_TESTNAME=test_surf_simple -testplusarg UVM_VERBOSITY=UVM_MEDIUM
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
